rfb_cnpj:
  target: prod
  outputs:
    prod:
      type: duckdb
      extensions:
        - parquet
      threads: 6

      path: ../data/rfb-cnpj.duckdb

      # Default location for materialized='external' files
      #   https://github.com/duckdb/dbt-duckdb#reading-and-writing-external-files
      external_root: ../data/2-parquet_sources 
