-- csv_estabelecimento.sql
SELECT
    cnpj_base,
    cnpj_ordem,
    cnpj_dv,
    CAST(matriz == '1' AS BOOLEAN) AS matriz,
    nome_fantasia,
    situacao_cadastral,
    data_situacao_cadastral,
    motivo_situacao_cadastral,
    nome_cidade_exterior,
    pais,
    data_inicio_atividades,
    cnae,
    cnae_secundario,
    tipo_logradouro,
    logradouro,
    CASE WHEN numero IN ('S/N', 'SN', 'S N', 'sn', 's/n', 'S/Nº', 'S/N.', '-', 'S/NR', '.', 'Sn', 'SNR', 'S.N', 'S-N', 'SEM', 'SEM NM', 'SEM NU', 'S\N', 'S/n', '0', '00', '000', '0000', '00000', '000000') THEN NULL ELSE numero END AS numero,
    complemento,
    bairro,
    LPAD(cep, 8, '0') AS cep,
    uf,
    municipio,
    ddd1,
    telefone1,
    ddd2,
    telefone2,
    ddd_fax,
    fax,
    LOWER(correio_eletronico) AS correio_eletronico,
    situacao_especial,
    data_situacao_especial,
    format('{:t.}/{:04d}-{:02d}', 100000000 + CAST(cnpj_base AS INTEGER), CAST(cnpj_ordem AS INTEGER), CAST(cnpj_dv AS INTEGER))[2:19] AS cnpj
FROM
    read_csv("../data/1-csv_sources/*.ESTABELE",
             header = false,
             columns = {'cnpj_base': 'UINTEGER',
                        'cnpj_ordem': 'USMALLINT',
                        'cnpj_dv': 'UTINYINT',
                        'matriz': 'VARCHAR',
                        'nome_fantasia': 'VARCHAR',
                        'situacao_cadastral': 'UTINYINT',
                        'data_situacao_cadastral': 'DATE',
                        'motivo_situacao_cadastral': 'UTINYINT',
                        'nome_cidade_exterior': 'VARCHAR',
                        'pais': 'VARCHAR',
                        'data_inicio_atividades': 'DATE',
                        'cnae': 'VARCHAR',
                        'cnae_secundario': 'VARCHAR',
                        'tipo_logradouro': 'VARCHAR',
                        'logradouro': 'VARCHAR',
                        'numero': 'VARCHAR',
                        'complemento': 'VARCHAR',
                        'bairro': 'VARCHAR',
                        'cep': 'VARCHAR',
                        'uf': 'VARCHAR',
                        'municipio': 'USMALLINT',
                        'ddd1': 'VARCHAR',
                        'telefone1': 'VARCHAR',
                        'ddd2': 'VARCHAR',
                        'telefone2': 'VARCHAR',
                        'ddd_fax': 'VARCHAR',
                        'fax': 'VARCHAR',
                        'correio_eletronico': 'VARCHAR',
                        'situacao_especial': 'VARCHAR',
                        'data_situacao_especial': 'DATE'},
             dateformat = '%Y%M%d',
             nullstr = ['', '0'],
             decimal_separator = ',',
             delim = ';')
